### ISSUE TITLE
[Bug] missed in init section dragonwell 8 docker image

### ISSUE THREAD

**Issue by kk60195** [alibaba/dragonwell8#101]
**Description**
See no visible gains from dragonwell. the printouts say "is missed in init section" alot when running it

**Steps to Reproduce**
1. use image 
FROM registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.3.3-GA_alpine_x86_64_8u242-b98
2. Run a Spring boot microservice in the image
3.  Actual java command: 

exec java
-XX:-ClassUnloading \
-XX:-CMSClassUnloadingEnabled \
-XX:-ClassUnloadingWithConcurrentMark \
-XX:CompilationWarmUpLogfile=jwarmup.log \
-XX:+CompilationWarmUpRecording \
-XX:CompilationWarmUpRecordTime=300 \
-jar \
-Dspring.profiles.active=$ENVIRONMENT \
/usr/opt/service/$SERVICE_NAME.jar

4. docker run the image. Docker exec into the container and copy out the jwarmup.log(i see jwarmup.log is generated after 300 seconds) after hitting the container with some load tests.

5. Create a separate docker image as previous. but this time copy in jwarmup.log
ADD ./dragonwell/jwarmup.log /jwarmup.log 

6. New image run with java
exec java \
-XX:+CompilationWarmUp \
-XX:-TieredCompilation \
-XX:CompilationWarmUpLogfile=jwarmup.log \
-XX:CompilationWarmUpDeoptTime=0 \
-jar \
-Dspring.profiles.active=$ENVIRONMENT \
/usr/opt/service/$SERVICE_NAME.jar

7. Docker run and see printout. No visible gains from startup. still need to run gatling against the endpoint for a couple minutes before response time comes down.

8. ( actual error) during the second run with jwarmup. Console keeps printing

[JitWarmUp] WARNING : class org/springframework/core/SimpleAliasRegistry$$Lambda$217 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/metrics/web/servlet/WebMvcMetricsFilter$$Lambda$1046 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/context/properties/source/ConfigurationPropertyName$$Lambda$81 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/trace/http/HttpExchangeTracer$FilteredTraceableResponse$$Lambda$1045 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/trace/http/HttpExchangeTracer$FilteredTraceableRequest$$Lambda$705 is missed in init section
[JitWarmUp] WARNING : class org/springframework/cache/annotation/AnnotationCacheOperationSource$$Lambda$251 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/trace/http/HttpExchangeTracer$$Lambda$1041 is missed in init section
[JitWarmUp] WARNING : class java/lang/invoke/LambdaForm$MH is missed in init section
[JitWarmUp] WARNING : class org/springframework/util/LinkedCaseInsensitiveMap$$Lambda$1004 is missed in init section
[JitWarmUp] WARNING : class sun/management/LazyCompositeData$$Lambda$386 is missed in init section
[JitWarmUp] WARNING : class org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor$$Lambda$212 is missed in init section
[JitWarmUp] WARNING : class java/util/stream/Collectors$$Lambda$494 is missed in init section
[JitWarmUp] WARNING : class java/util/stream/Collectors$$Lambda$49 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/autoconfigure/condition/OnPropertyCondition$$Lambda$157 is missed in init section
[JitWarmUp] WARNING : class com/tvg/fcp/configuration/CustomExecutorService$$Lambda$1010 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/trace/http/HttpExchangeTracer$FilteredTraceableRequest$$Lambda$702 is missed in init section
[JitWarmUp] WARNING : class org/springframework/util/ReflectionUtils$$Lambda$176 is missed in init section
[JitWarmUp] WARNING : class java/util/stream/Collectors$$Lambda$88 is missed in init section
[JitWarmUp] WARNING : class java/lang/invoke/LambdaForm$DMH is missed in init section
[JitWarmUp] WARNING : class java/util/stream/StreamSpliterators$WrappingSpliterator$$Lambda$76 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/actuate/web/trace/servlet/HttpTraceFilter$$Lambda$1038 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/autoconfigure/condition/BeanTypeRegistry$$Lambda$180 is missed in init section
[JitWarmUp] WARNING : class org/springframework/boot/autoconfigure/AutoConfigurationSorter$AutoConfigurationClasses$$Lambda$154 is missed in init section
[[JitWarmUp] WARNING : class org/springframework/boot/actuate/trace/http/HttpExchangeTracer$FilteredTraceableRequest$$Lambda$702 is missed in init section
[JitWarmUp] WARNING : class org/springframework/web/method/ControllerAdviceBean$$Lambda$542 is missed in init section

**Expected behavior**
Some visible change in startup cpu usage of container

**JDK version**
The output of `java -version` command
This is from your image( openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.3.3) (build 1.8.0_242-b98)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.3.3) (build 25.242-b98, mixed mode))

**Execution environment**
 - OS and version: docker --version
Docker version 19.03.8, build afacb8b
 - CPU model: on a macbook. but using docker
 - Number of CPU cores: 
        docker --cpu=0.5
 - Size of physical memory: 
        5 gb allowed
 - Inside Linux container? 
         yes. 
docker run -ti --cpus=0.5 --env SERVICE_NAME=XXXXXX -p 9991:8080 imagename:dragonwell /bin/sh
   - Linux container name (docker, pouch, etc): 
            registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.3.3-GA_alpine_x86_64_8u242-b98
   - Linux container version:

**Comment by luchsh** [comment]
Thanks for reporting, @kuaiwei  please take a look.

**Comment by kuaiwei** [comment]
Hi Kuan,
 
   These warning messages could be ignored because most of these classes are generated at runtime and JWarmup can not identify them at warmup phase. We may remove these warning messages in future release.

  Now user need invoke an api to trigger warmup compilation. It could be done via jcmd. Do you invoke the api ?

Thanks,
Kuai Wei

**Comment by kk60195** [comment]
Hi Kuai,

Is this done through the actual java code, a flag set during the exec java? or something in bash depending on the machine state? Documentation around this process is limited so i'm not too sure how this is 'invoked'. Is my method of creating one image for creating jwarmup.log  and then copying over the jwarmup.log into another image to run even the correct procedure?

Best,
Kuan Chen

**Comment by kuaiwei** [comment]
The jwarmup api can be invoked either by java code or by shell command. I think jcmd is a convenient way because it doesn't require change in application. The usage was described in release notes. ( https://github.com/alibaba/dragonwell8/wiki/Alibaba-Dragonwell8-Release-Notes#jwarmup ) .
The time to invoke api is important to jwarmup. It's better to use it after application is startup and before the actual traffic is handled.

Kuai Wei

**Comment by kk60195** [comment]
is the command suppose to be :  'jcmd <pid> JWarmup -notify'? wouldn't this command move the class loading to the end of the container startup instead of the start of jar execution? Where in the JFR Mission Control do i see the savings? Compilations tab? Processes tab?

**Comment by kuaiwei** [comment]
Hi Kuan,
My comment is inline.

is the command suppose to be : 'jcmd pid JWarmup -notify'? 
kw : yes, it's the command to trigger warmup compilation

wouldn't this command move the class loading to the end of the container startup instead of the start of jar execution?  
kw : It doesn't change order of class loading.

Where in the JFR Mission Control do i see the savings? Compilations tab? Processes tab?
kw : not clear about it. Do you want to see effect of warmup? We use some system monitor tool to check cpu usage/response time when requests are handled. I think JFR MC can monitor cpu usage as well.

I'm doing mvn install for my application using adoptOpenjdk11 on a mac. is there a jar for com.alibaba.jwarmup i can include in the directory to use inside the code?
kw : Dragonwell8 provides a mocking api package for develop. For example, https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.3.3-GA/java8-api-8.3.3.jar is the api package for 8.3.3 . But we have not port jwarmup to Dragonwell11. Do you want to use it in JDK11 ?

Best,
Kuai Wei
