### ISSUE TITLE
[question] Conditions to compile method in C2 Compiler with JWarmUp log

### ISSUE THREAD

**Issue by furson** [alibaba/dragonwell8#123]
**Description**
Hi, thanks for reading it.

**Comment by furson** [comment]
I wanna to know is there any condition to compile method in C2 Compiler with JWarmUp log. I got a log which records jar path, class name and classLoader name and use it to have another jvm run. In the another run, I'm not get all methods compilation in C2. I just simple run my jvm and get the log without any specific run to make the hotspot method. Should I make my methods to compile in C2 during the recording run.

**Comment by zhangruoxu** [comment]
Hi furson,  
Thanks for reporting. I will take a look at this issue and update you as soon as possible. Cheers :-)

**Comment by zhangruoxu** [comment]
Hi furson,

JWarmup compilation needs to be triggered manually. 
You could use `jcmd` to trigger JWarmup compilation. 
Usage:
```
jcmd <pid> JWarmup -notify
```
Use `jcmd <pid> JWarmup -help` to obtain more details. 

I hope this reply is helpful. Please feel free to ask any questions. 

Cheers,
Yifei

**Comment by furson** [comment]
Hi Yifie,
Thanks for your reply. After reading your reply, I still have some questions about JWarmUp.
**Question about how to trigger JWarmUp Compilation**
> JWarmup compilation needs to be triggered manually.
So is it means that after recording JWarmUp log and using options -XX:+CompilationWarmUp -XX:-TieredCompilation -XX:CompilationWarmUpLogfile to start jvm, we still need to trigger manually if we want better performance improved by JWarmUp? If it's necessary, I think it's better to write clearer in user guide.
**Question about how to record JWarmUp log**
Is there only methods compiled by C2 Compilation would be recorded if I don't use CompilationWarmUpRecordMinLevel options to change JWarmUp logging method level. What would the logging file changed if I set CompilationWarmUpRecordMinLevel to 0.

**Comment by zhangruoxu** [comment]
Hi furson,

Dragonwell user guide mentions how the warmup compilation is triggered. 
> Trigger compilation at appropriate time after all necessary initialization work of your application is done, call the following API to notify JVM: com.alibaba.jwarmup.JWarmUp.notifyApplicationStartUpIsDone() After that, the methods will be compiled by JVM proactively.

The reason is that classes at least need to be loaded before compilation, or those compiled methods are de-optimized very quickly (because classes are not loaded), which makes the pre-compilation in vain. 

The problem JWarmup wants to solve is that user threads preempt compiler threads when bursty data traffic coming into the system, which delays Java code to be efficiently compiled by the C2 compiler. To this end, JWarmup triggers C2 compilation after necessary Java application initialization has finished but before data traffic coming into the system. 

Moreover, according to the user guide, `com.alibaba.jwarmup.JWarmUp.notifyApplicationStartUpIsDone()` needs to be invoked to notify JVM to perform warmup compilation. Since this usually requires users to modify code to do that, Dragonwell supports using `jcmd` to trigger JWarmup compilation.

For the second question, you could turn off the tiered compilation, i.e. `-XX:-TieredCompilation`, therefore, only C2 compilation is recorded. 

cheers,
Yifei
