### ISSUE TITLE
[Bug] NoClassDefFoundError when load com.sum.corba.se.* in rt.jar

### ISSUE THREAD

**Issue by FalconIA** [alibaba/dragonwell8#130]
**Description**
Throwed a `NoClassDefFoundError` when call `com.sum.corba.se.*` in `rt.jar` . 
It occurs under official dragonwell docker, but works well under windows (build 1.8.0_262-b10).

**Steps to Reproduce**
1. Run spring-boot executable jar in official dragonwell docker. (The jar include `org.jacorb:jacorb:3.8`)
2. Call `org.jacorb.orb.ORB#string_to_object(java.lang.String)`
4. See error:
```
Caused by: java.lang.NoClassDefFoundError: com/sun/corba/se/impl/orbutil/GetPropertyAction
        at javax.rmi.CORBA.Stub.createDelegate(Unknown Source) ~[na:1.8.0_262]
        at javax.rmi.CORBA.Stub.<clinit>(Unknown Source) ~[na:1.8.0_262]
        at org.jacorb.org.Delegate.getReference(Delegate.java:1143) ~[jacorb-3.8.jar!/:3.8]
        at org.jacorb.org.ORB._getDelegate(ORB.java:588) ~[jacorb-3.8.jar!/:3.8]
        at org.jacorb.org.ORB.string_to_object(ORB.java:2466) ~[jacorb-3.8.jar!/:3.8]
```

**Expected behavior**
No NoClassDefFoundError throwed.

**JDK version**
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.4.4) (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.4.4) (build 25.262-b10, mixed mode)
```
(Docker Image: registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.4.4-GA_alpine_x86_64_8u262-b10_slim)

**Execution environment**
 - Inside Linux container? Yes
   - Linux container name (docker, pouch, etc): docker
   - Linux container version: 19.03.12

**Comment by zhengxiaolinX** [comment]
Thanks for reporting. We use AdoptOpenJDK's docker file to generate a slim version of docker images of Alpine Linux platform. It will trim some uncommon files, such as `com/sun/corba`, please see `https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/ubi/slim-java_rtjar_del.list#L23` as we discussed in the Ding group. So in fact not a problem. Please use the `registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.4.4-GA_alpine_x86_64_8u262-b10` version instead of the slim one. Please feel free to reopen this issue.
