### ISSUE TITLE
What's the difference between "Dragonwell" and "Alibaba JDK" ?

### ISSUE THREAD

**Issue by simonis** [alibaba/dragonwell8#17]
Congratulations for finally releasing Dragonwell!!!

I saw the presentation "[Extreme Scaling with Alibaba JDK](https://assets.ctfassets.net/oxjq45e8ilak/7J537sIeZisGIgwe4qyAE6/33503896530097133df7e7cdaa7837db/Sanhong_Extreme_Scaling_with_Alibaba_JDK.pdf)" ([recording](https://youtu.be/94eTZsNYYBE)).

It mentions a bunch of features like Multi-tenant, GCIH, Wisp, JWarmup, ZProfiler. Are they, or will they all eventually be part of Dragonwell?

As far as I understood, not all of the mentioned "Alibaba JDK" features are Java SE 8 compatible. What are your future plans for such features? Will you integrate them into Dragonwell nevertheless (thus making Dragonwell incompatible to Java SE 8), will you maintain an extra version/branch with such features or do you not plan to bring such features into Dragonwell at all?

Please don't get me wrong. I like all the mentioned "Alibaba JDK" features and I'd love to see them in Dragonwell (or any other open source, OpenJDK version).

Thanks,
Volker

**Comment by sanhong** [comment]
HI Volker,
Glad you come to Alibaba Dragonwell and thanks for your comments.

Generally,  we would like to contribute all the features in AlibabaJDK up into OpenJDK[(see Alibaba-Dragonwell8-FAQ)](https://github.com/alibaba/dragonwell8/wiki/Alibaba-Dragonwell8-FAQ).  JFR(for JDK8u),  JWarmup(for tip) are real examples we are doing now in progress. 

The reality, as you have known,  is the contribution to upsteam generally requires much longer process , may not be possible due to the various players/interests. We hope Dragonwell as downstream of OpenJDK is used as a simple way to maintain these "extra" features, so that we can quickly react on  customer requests and be able to deliver the fixes for them.

**Comment by simonis** [comment]
Hi Sanhong,

thanks for your answer!
Looking forward to also see all the other "Alibaba JDK" features in Dragonwell.

Also wishing you all the best for bringing your features upstream :)

Best regards,
Volker
